### ISSUE TITLE
Does not  compile with Material UI v.0.12.4

### ISSUE THREAD

**Issue by rdagger** [rkstar/meteor-material-ui-example#4]
The example will not compile if you change the Material UI version in packages.json file from 0.12.1 to 0.12.4.  It throws an error when you run meteor:

```
C:\Users\Registered User\meteor\meteor-material-ui-example2\.meteor\local\build\programs\server\app\lib\config\app.browserify.js:13953
  propTypes: {     // 42
  ^^^^^^^^^
SyntaxError: Duplicate data property in object literal not allowed in strict mode
at Array.forEach (native)
at Function._.each._.forEach (C:\Users\Registered User\AppData\Local\.meteor\packages\meteor-tool\1.1.9\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\underscore\underscore.js:79:11)
at C:\Users\Registered User\meteor\meteor-material-ui-example2\.meteor\local\build\programs\server\boot.js:137:5
```

It works with 0.12.1, 0.12.2 and 0.12.3 (just not 0.12.4).  It is possible to compile with 0.12.3 and then update to 0.12.4.  Thank you for this very helpful example.

**Comment by rkstar** [comment]
you're right.  this was an error acknowledged by the material-ui team in 0.12.4.  they suggested using 0.12.5 or 0.12.3 instead.

since then, they've updated their library to 0.13.2 which works with react 0.14.2 (also now available via [meteor/react-packages](https://github.com/meteor/react-packages/))
